Fixes #18284 - Remove docker_port_t definition
theforeman/foreman-selinux pull request #66
Opened 2017-01-27 14:49 UTC by dLobatog

docker_port_t is defined on container-selinux. We could make
foreman-selinux depend on container-selinux to be able to install both
modules together on the same computer.

2017-01-27 15:26 UTC, domcleal requested changes
The policy should probably be removed and maintained by the foreman_docker plugin, so as not to introduce any dependencies in Foreman on Docker or container policy.

2017-01-27 15:26 UTC, domcleal commented on foreman.te
>      allow passenger_t docker_port_t:tcp_socket name_connect;
Shouldn't this be optional policy if dependent on an additional module, and also conditional on `has_docker` too?

2017-01-30 11:27 UTC, lzap commented on foreman.te
>      allow passenger_t docker_port_t:tcp_socket name_connect;
Yes, this could help. But you made a good point on extracting this into separate package. That would be much cleaner.

2017-01-31 15:23 UTC, lzap commented
Alternative proposal, let's completely remove docker from our policy and we can only test for docker_port_t in the `enable` script, if present, we will enable it.

And for the upgrade path, once we remove our policy, the docker policy that can't load will load fine. This should work.

2017-03-08 14:19 UTC, lzap commented
@dLobatog are you planning to work on that? Dan also recommends to define the docker type this way: https://github.com/projectatomic/container-selinux/pull/26#issuecomment-284435882

2017-09-01 13:51 UTC, lzap commented
Replaced with https://github.com/theforeman/foreman-selinux/pull/68

2017-09-01 13:51 UTC, closed without merging